### ISSUE TITLE
Undefined index: contentType in GoogleCloudStorageAdapter.php line 473

### ISSUE THREAD

**Issue by emilv** [cedricziel/flysystem-gcs#9]
We get the following error when calling `Storage::disk('gcs')->listContents('ftp/pyramid')`:

```
In GoogleCloudStorageAdapter.php line 473:

  [ErrorException]
  Undefined index: contentType


Exception trace:
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/aroma-pos/vendor/cedricziel/flysystem-gcs/src/GoogleCloudStorageAdapter.php:473
 CedricZiel\FlysystemGcs\GoogleCloudStorageAdapter->convertObjectInfo() at /var/www/aroma-pos/vendor/cedricziel/flysystem-gcs/src/GoogleCloudStorageAdapter.php:334
 CedricZiel\FlysystemGcs\GoogleCloudStorageAdapter->listContents() at /var/www/aroma-pos/vendor/league/flysystem/src/Filesystem.php:271
 League\Flysystem\Filesystem->listContents() at n/a:n/a
 call_user_func_array() at /var/www/aroma-pos/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:682
 Illuminate\Filesystem\FilesystemAdapter->__call() at /var/www/aroma-pos/app/Console/Commands/ImportFromPyramid.php:102
 App\Console\Commands\ImportFromPyramid->initFileList() at /var/www/aroma-pos/app/Console/Commands/ImportFromPyramid.php:84
```

![skarmdump 2018-01-26t09 54 16](https://user-images.githubusercontent.com/1684914/35431982-e37f4ea2-027e-11e8-8211-2daacef1cb7e.png)

**Comment by emilv** [comment]
I added a `dd` right before that row and got this:

![skarmdump 2018-01-26t10 09 19](https://user-images.githubusercontent.com/1684914/35432671-0f1ff2c6-0281-11e8-965d-3f8b9a1e37b9.png)

And this is what the object looks like with `gsutil stat`:

![skarmdump 2018-01-26t10 15 10](https://user-images.githubusercontent.com/1684914/35432907-e6135fd4-0281-11e8-8af4-123290cd7229.png)

So apparently there is no Content-Type! The files are created with the gcsfuse filesystem, if that matters.

**Comment by emilv** [comment]
This seems to be expected behavior from gcsfuse when the MIME type is unknown: https://github.com/GoogleCloudPlatform/gcsfuse/issues/160

So apparently `Content-Type` is not a mandatory field.

**Comment by cedricziel** [comment]
Thanks for the detailed analysis! Would you be able to provide a pull request for this?
